import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
from datetime import datetime

async def seed_real_restaurants():
    client = AsyncIOMotorClient('mongodb+srv://weeat_userr:123455@cluster01.rsszzqs.mongodb.net/?appName=Cluster01')
    db = client['weeat']
    
    # Clear existing restaurants
    await db.restaurants.delete_many({})
    print("Cleared existing restaurants")
    
    restaurants = [
        # Fast Food Chains
        {
            "name": "KFC",
            "cuisine": "Fast Food",
            "address": "Dubai Mall, Financial Center Road, Downtown Dubai",
            "phone": "+971 4 339 9888",
            "lat": 25.1972,
            "lng": 55.2744,
            "imageUrl": "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=500",
            "rating": 4.2,
            "opening_hours": "10:00 AM - 12:00 AM",
            "price_range": "$$",
            "description": "World-famous fried chicken chain",
            "createdAt": datetime.utcnow().isoformat(),
        },
        {
            "name": "McDonald's",
            "cuisine": "Fast Food",
            "address": "Sheikh Zayed Road, Trade Centre Area, Dubai",
            "phone": "+971 4 330 8888",
            "lat": 25.2177,
            "lng": 55.2795,
            "imageUrl": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500",
            "rating": 4.0,
            "opening_hours": "Open 24 Hours",
            "price_range": "$",
            "description": "Iconic burgers, fries, and shakes",
            "createdAt": datetime.utcnow().isoformat(),
        },
        {
            "name": "Burger King",
            "cuisine": "Fast Food",
            "address": "Mall of the Emirates, Al Barsha, Dubai",
            "phone": "+971 4 341 3555",
            "lat": 25.1181,
            "lng": 55.1988,
            "imageUrl": "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=500",
            "rating": 4.1,
            "opening_hours": "10:00 AM - 12:00 AM",
            "price_range": "$$",
            "description": "Flame-grilled burgers and more",
            "createdAt": datetime.utcnow().isoformat(),
        },
        {
            "name": "Subway",
            "cuisine": "Fast Food",
            "address": "Jumeirah Beach Road, Jumeirah 1, Dubai",
            "phone": "+971 4 344 7777",
            "lat": 25.2285,
            "lng": 55.2594,
            "imageUrl": "https://images.unsplash.com/photo-1553909489-cd47e0907980?w=500",
            "rating": 3.9,
            "opening_hours": "9:00 AM - 11:00 PM",
            "price_range": "$",
            "description": "Fresh subs and salads made your way",
            "createdAt": datetime.utcnow().isoformat(),
        },
        {
            "name": "Papa John's",
            "cuisine": "Pizza",
            "address": "Al Wasl Road, Jumeirah 2, Dubai",
            "phone": "+971 4 344 4444",
            "lat": 25.2197,
            "lng": 55.2534,
            "imageUrl": "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=500",
            "rating": 4.3,
            "opening_hours": "10:00 AM - 1:00 AM",
            "price_range": "$$",
            "description": "Better ingredients, better pizza",
            "createdAt": datetime.utcnow().isoformat(),
        },
        
        # Casual Dining
        {
            "name": "The Cheesecake Factory",
            "cuisine": "American",
            "address": "Dubai Mall, Financial Center Road, Downtown Dubai",
            "phone": "+971 4 330 6677",
            "lat": 25.1985,
            "lng": 55.2716,
            "imageUrl": "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=500",
            "rating": 4.5,
            "opening_hours": "10:00 AM - 12:00 AM",
            "price_range": "$$$",
            "description": "Famous for cheesecakes and American cuisine",
            "createdAt": datetime.utcnow().isoformat(),
        },
        {
            "name": "TGI Friday's",
            "cuisine": "American",
            "address": "Ibn Battuta Mall, Jebel Ali Village, Dubai",
            "phone": "+971 4 368 5666",
            "lat": 25.0431,
            "lng": 55.1193,
            "imageUrl": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=500",
            "rating": 4.2,
            "opening_hours": "11:00 AM - 12:00 AM",
            "price_range": "$$$",
            "description": "Casual dining with American favorites",
            "createdAt": datetime.utcnow().isoformat(),
        },
        {
            "name": "Chili's",
            "cuisine": "American",
            "address": "Deira City Centre, Port Saeed, Dubai",
            "phone": "+971 4 295 8888",
            "lat": 25.2528,
            "lng": 55.3321,
            "imageUrl": "https://images.unsplash.com/photo-1544025162-d76694265947?w=500",
            "rating": 4.1,
            "opening_hours": "11:00 AM - 12:00 AM",
            "price_range": "$$$",
            "description": "Southwestern-inspired casual dining",
            "createdAt": datetime.utcnow().isoformat(),
        },
        
        # Middle Eastern
        {
            "name": "Al Mallah",
            "cuisine": "Lebanese",
            "address": "Al Dhiyafa Road, Satwa, Dubai",
            "phone": "+971 4 331 1888",
            "lat": 25.2285,
            "lng": 55.2716,
            "imageUrl": "https://images.unsplash.com/photo-1541518763669-27fef04b14ea?w=500",
            "rating": 4.6,
            "opening_hours": "7:00 AM - 2:00 AM",
            "price_range": "$$",
            "description": "Authentic Lebanese street food since 1979",
            "createdAt": datetime.utcnow().isoformat(),
        },
        {
            "name": "Zaroob",
            "cuisine": "Lebanese",
            "address": "Sheikh Zayed Road, Trade Centre Area, Dubai",
            "phone": "+971 4 339 2222",
            "lat": 25.2177,
            "lng": 55.2834,
            "imageUrl": "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=500",
            "rating": 4.4,
            "opening_hours": "Open 24 Hours",
            "price_range": "$$",
            "description": "Modern Lebanese street food",
            "createdAt": datetime.utcnow().isoformat(),
        },
        {
            "name": "Operation: Falafel",
            "cuisine": "Lebanese",
            "address": "Jumeirah Beach Road, Jumeirah 1, Dubai",
            "phone": "+971 4 344 7777",
            "lat": 25.2285,
            "lng": 55.2594,
            "imageUrl": "https://images.unsplash.com/photo-1593001874117-c99c800e3eb7?w=500",
            "rating": 4.3,
            "opening_hours": "8:00 AM - 12:00 AM",
            "price_range": "$",
            "description": "Fresh falafel and Middle Eastern wraps",
            "createdAt": datetime.utcnow().isoformat(),
        },
        
        # Asian
        {
            "name": "P.F. Chang's",
            "cuisine": "Chinese",
            "address": "Dubai Mall, Financial Center Road, Downtown Dubai",
            "phone": "+971 4 339 8888",
            "lat": 25.1985,
            "lng": 55.2716,
            "imageUrl": "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=500",
            "rating": 4.4,
            "opening_hours": "11:00 AM - 12:00 AM",
            "price_range": "$$$",
            "description": "Asian fusion dining experience",
            "createdAt": datetime.utcnow().isoformat(),
        },
        {
            "name": "Yo! Sushi",
            "cuisine": "Japanese",
            "address": "Mall of the Emirates, Al Barsha, Dubai",
            "phone": "+971 4 341 3555",
            "lat": 25.1181,
            "lng": 55.1988,
            "imageUrl": "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=500",
            "rating": 4.2,
            "opening_hours": "11:00 AM - 11:00 PM",
            "price_range": "$$$",
            "description": "Conveyor belt sushi and Japanese dishes",
            "createdAt": datetime.utcnow().isoformat(),
        },
        {
            "name": "Wagamama",
            "cuisine": "Japanese",
            "address": "Dubai Marina Walk, Dubai Marina, Dubai",
            "phone": "+971 4 392 7777",
            "lat": 25.0776,
            "lng": 55.1340,
            "imageUrl": "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500",
            "rating": 4.3,
            "opening_hours": "11:00 AM - 11:00 PM",
            "price_range": "$$",
            "description": "Japanese-inspired noodle and rice dishes",
            "createdAt": datetime.utcnow().isoformat(),
        },
        {
            "name": "Nando's",
            "cuisine": "Portuguese",
            "address": "City Walk, Al Safa, Dubai",
            "phone": "+971 4 344 7777",
            "lat": 25.2085,
            "lng": 55.2616,
            "imageUrl": "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=500",
            "rating": 4.5,
            "opening_hours": "11:00 AM - 12:00 AM",
            "price_range": "$$",
            "description": "Flame-grilled peri-peri chicken",
            "createdAt": datetime.utcnow().isoformat(),
        },
        
        # Cafes
        {
            "name": "Starbucks",
            "cuisine": "Cafe",
            "address": "Dubai Marina Walk, Dubai Marina, Dubai",
            "phone": "+971 4 392 8888",
            "lat": 25.0776,
            "lng": 55.1340,
            "imageUrl": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=500",
            "rating": 4.1,
            "opening_hours": "6:00 AM - 12:00 AM",
            "price_range": "$$",
            "description": "World-famous coffeehouse chain",
            "createdAt": datetime.utcnow().isoformat(),
        },
        {
            "name": "Tim Hortons",
            "cuisine": "Cafe",
            "address": "JBR Walk, Jumeirah Beach Residence, Dubai",
            "phone": "+971 4 392 7777",
            "lat": 25.0806,
            "lng": 55.1340,
            "imageUrl": "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=500",
            "rating": 4.0,
            "opening_hours": "6:00 AM - 12:00 AM",
            "price_range": "$",
            "description": "Canadian coffee and donuts chain",
            "createdAt": datetime.utcnow().isoformat(),
        },
        
        # Pizza
        {
            "name": "Pizza Hut",
            "cuisine": "Pizza",
            "address": "Al Rigga Road, Deira, Dubai",
            "phone": "+971 4 295 8888",
            "lat": 25.2528,
            "lng": 55.3321,
            "imageUrl": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=500",
            "rating": 4.0,
            "opening_hours": "10:00 AM - 1:00 AM",
            "price_range": "$$",
            "description": "Classic pizza chain with delivery",
            "createdAt": datetime.utcnow().isoformat(),
        },
        {
            "name": "Domino's Pizza",
            "cuisine": "Pizza",
            "address": "Jumeirah Lake Towers, Dubai",
            "phone": "+971 4 392 8888",
            "lat": 25.0776,
            "lng": 55.1340,
            "imageUrl": "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=500",
            "rating": 4.1,
            "opening_hours": "10:00 AM - 2:00 AM",
            "price_range": "$$",
            "description": "Pizza delivery experts",
            "createdAt": datetime.utcnow().isoformat(),
        },
        
        # Ice Cream & Desserts
        {
            "name": "Baskin-Robbins",
            "cuisine": "Desserts",
            "address": "The Walk at JBR, Jumeirah Beach Residence, Dubai",
            "phone": "+971 4 392 7777",
            "lat": 25.0806,
            "lng": 55.1340,
            "imageUrl": "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=500",
            "rating": 4.2,
            "opening_hours": "10:00 AM - 12:00 AM",
            "price_range": "$",
            "description": "31 flavors of ice cream",
            "createdAt": datetime.utcnow().isoformat(),
        },
        
        # Fine Dining
        {
            "name": "Pierchic",
            "cuisine": "Seafood",
            "address": "Al Qasr Hotel, Madinat Jumeirah, Dubai",
            "phone": "+971 4 366 6705",
            "lat": 25.1306,
            "lng": 55.1840,
            "imageUrl": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=500",
            "rating": 4.8,
            "opening_hours": "12:30 PM - 3:00 PM, 6:30 PM - 11:00 PM",
            "price_range": "$$$$",
            "description": "Overwater seafood restaurant with stunning views",
            "createdAt": datetime.utcnow().isoformat(),
        },
        {
            "name": "Zuma",
            "cuisine": "Japanese",
            "address": "DIFC, Gate Village 6, Dubai",
            "phone": "+971 4 425 5660",
            "lat": 25.2177,
            "lng": 55.2795,
            "imageUrl": "https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=500",
            "rating": 4.7,
            "opening_hours": "12:00 PM - 3:00 PM, 7:00 PM - 12:00 AM",
            "price_range": "$$$$",
            "description": "Contemporary Japanese cuisine",
            "createdAt": datetime.utcnow().isoformat(),
        },
        
        # Local Favorites
        {
            "name": "Ravi Restaurant",
            "cuisine": "Pakistani",
            "address": "Al Satwa Road, Satwa, Dubai",
            "phone": "+971 4 331 5353",
            "lat": 25.2285,
            "lng": 55.2716,
            "imageUrl": "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500",
            "rating": 4.4,
            "opening_hours": "6:00 AM - 2:00 AM",
            "price_range": "$",
            "description": "Legendary Pakistani restaurant since 1978",
            "createdAt": datetime.utcnow().isoformat(),
        },
        {
            "name": "Karachi Darbar",
            "cuisine": "Pakistani",
            "address": "Al Karama, Dubai",
            "phone": "+971 4 334 7777",
            "lat": 25.2385,
            "lng": 55.2916,
            "imageUrl": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=500",
            "rating": 4.3,
            "opening_hours": "Open 24 Hours",
            "price_range": "$",
            "description": "Authentic Pakistani and Indian cuisine",
            "createdAt": datetime.utcnow().isoformat(),
        },
    ]
    
    await db.restaurants.insert_many(restaurants)
    print(f"Added {len(restaurants)} real restaurants!")
    
    # Show summary
    for r in restaurants:
        print(f"  {r['name']} - {r['cuisine']} - {r['address'][:40]}...")

asyncio.run(seed_real_restaurants())